# Configuration for Shape Generator model

# Model configuration
model:
  name: ShapeGenerator
  latent_dim: 128
  hidden_dim: 256
  num_points: 2048
  use_templates: True
  use_pretrained_extractor: True
  shape_refinement: True
  use_halton: True  # Use Halton sequence for better point distribution
  use_graph_attention: True  # Use graph attention for structural understanding

# Graph attention parameters
graph_attention:
  num_heads: 4
  num_layers: 3
  hidden_dim: 128
  dropout: 0.1
  k_neighbors: 20

# Halton sampling parameters
halton:
  scale: 0.8
  center: True
  noise_scale: 0.05
  post_process: True
  shape_refinement: true  # Apply shape refinement for exact resemblance

# Data configuration
data:
  categories: ['all']  # Can be 'all' or list of specific categories
  augmentation: true  # Whether to use data augmentation
  normalize: true  # Whether to normalize point clouds

# Training configuration
training:
  seed: 42  # Random seed for reproducibility
  batch_size: 16  # Batch size for training
  epochs: 200  # Number of training epochs
  learning_rate: 0.0002  # Initial learning rate
  min_learning_rate: 0.00001  # Minimum learning rate for scheduler
  weight_decay: 0.00001  # Weight decay for regularization
  grad_clip: 1.0  # Gradient clipping value
  num_workers: 4  # Number of data loading workers
  
  # Loss weights
  chamfer_weight: 1.0  # Weight for Chamfer distance loss
  emd_weight: 0.5  # Weight for Earth Mover's Distance loss
  diversity_weight: 0.1  # Weight for geometric diversity loss
  
  # Logging and checkpointing
  log_interval: 10  # Log training progress every N batches
  checkpoint_interval: 10  # Save checkpoints every N epochs
  visualization_interval: 5  # Generate sample visualizations every N epochs

# Generation configuration
generation:
  temperature: 0.8  # Sampling temperature (lower = more deterministic)
  num_inference_steps: 50  # Number of inference steps for iterative refinement
  refinement_method: 'poisson'  # Method for mesh refinement (poisson, alpha_shape)
  poisson_depth: 9  # Depth parameter for Poisson surface reconstruction
  alpha_value: 1.0  # Alpha value for alpha shape reconstruction
